### ISSUE TITLE
does not work on win 11

### ISSUE THREAD

**Issue by rovsita** [opentoonz/iwawarper#2]
I'm using google translate to write this, so I apologize if something doesn't make sense.

my operating system is win 11 with 4 ram, i can open the program and import images (png, tiff, jpg) but when i try to use any tool the program closes.

**Comment by RodneyBaker** [comment]
@rovsita You might wish to join the Opentoonz discord where there is a IwaWarper channel.
There we can help you get IwaWarper up and running on Win11.

Discord link:  https://discord.gg/UQxvYBKW5U

4MB of ram will definitely be problematic though.

**Comment by rovsita** [comment]
The program was able to run correctly after updating the drivers for my AMD graphics card. I regret the inconvenience I may have caused by responding so late.
